version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular
    container_name: 'angular'
    ports:
      - "4201:4200"
    expose:
      - "4201"

